### ISSUE TITLE
Can't boot the biospba

### ISSUE THREAD

**Issue by h-2** [r0m30/msed#11]
I have tried using the PBA, but no matter if it's flashed to a usb-disk or the shadow region of the SSD, my system won't boot from it. It just says that there are no valid boot devices. Anything I can do to help fix it? What kind of information do you require?

**Comment by r0m30** [comment]
What motherboard are you using and what is the bios firmware level?
Are you able to boot other usb images?

----------
Mike

On Sun, Feb 22, 2015 at 4:10 PM, Hannes Hauswedell <notifications@github.com

**Comment by h-2** [comment]
I am using an Asrock AM3+ Board ( I can lookup the exact model later). The SSD is a Samsung 850 EVO 250GB. I can boot other USB-images.
What do you mean by bios firmware level, the version I flashed from the project page? It was the most recent one, 0.20beta IIRC.

**Comment by h-2** [comment]
The Board-Model is: 890GM Pro3 R2.0

The detection of the disk, flashing the BPA to the shadow region etc all worked fine.

**Comment by r0m30** [comment]
That appears to be a UEFI motherboard.  At the moment msed doesn't have a
UEFI PBA.  The online user manual doesn't show a "legacy" or "CSM" boot
mode but since they talk about XP I believe they must have one. It may be
in the set boot order panel. If you find and set this you would have to
reinstall the OS as legacy/CSM as well.

I'm currently working on multiple locking ranges, when that is finished
then I plan on taking a serious look at UEFI support.  It looks like the
PBA will be much larger and probably have to reboot the system instead of
chain load it after UEFI support is added.

I'm don't like the reboot as a user experience but I haven't come across
any way to replicate the chain load functionality in UEFI.

----------
Mike

On Mon, Feb 23, 2015 at 1:48 PM, Hannes Hauswedell <notifications@github.com

**Comment by h-2** [comment]
> At the moment msed doesn't have a UEFI PBA. 

That explains it of course.

> If you find and set this you would have to reinstall the OS as legacy/CSM as well.

Hm, I am using plain FreeBSD which as of yet, doesn't come with UEFI support, so I think it must be in some kind of legacy mode, otherwise I couldn't boot it either, right? I will lookup the options in the UEFI anyway, later!

Thanks for your help!

**Comment by h-2** [comment]
I couldn't find any specific options in the UEFI, but I am pretty sure it supports booting in legacy mode, because it was one of very early UEFI boards, has support for non-EFI aware operating systems et cetera. Like I said before, I boot FreeBSD and Linux directly from the disk, without an extra EFI-partition or something like that..

**Comment by r0m30** [comment]
I can't figure out what is wrong.  I know that there was at least one person that got it to boot on a UEFI.
see here: http://vxlabs.com/tag/msed/

I don't know how/if GRUB handles UEFI/bios mixed mode booting. I'm wondering it the install is creating a hybrid partition table or something like that.

**Comment by h-2** [comment]
Hm, I have done some more tests... I cannot even boot your rescue image from a usb-stick. I can however just dd a debian netinstall .iso to the usb-disk and boot it. So maybe there is still some issue with your boot procedures in general?

If I open the boot device selection on boot (F11), I get 
  * SATA: Samsung SSD ...
  * USB Stick
  * SD Card reader
  * CF card reader 
  * UEFI Boot

So I think all other options except the last are always "BIOS compatibility boot". This would confirm my expectations, because it always just worked with everything else, and like I said FreeBSD doesn't even have UEFI support yet...

Thanks for your help!

**Comment by r0m30** [comment]
It's certainly possible that there is some issue with the format of the images. If you can't boot either the pba or the rescue image then it would definitely seem that there is at the very least a conflict with you bios.  One image uses syslinux and the other uses the extlinux variant of syslinux.  

Do you see anything at all displayed when you try to boot the usb-stick.  The vxlabs link above has a picture of what should be displayed when you boot.

Can you mount the usb-stick in linux?  Does the /boot partition contain the msedpba.c32 module, the lib*.c32 modules and the syslinux.cfg file?

Is the usb-stick a sandisk, with U3?

**Comment by h-2** [comment]
I don't see anything displayed at all...
Concerning the layout of the stick. this is strange. The partition layout on the usb-stick looks like this from FreeBSD:
```
% fdisk /dev/da4
******* Working on device /dev/da4 *******
parameters extracted from in-core disklabel are:
cylinders=487 heads=255 sectors/track=63 (16065 blks/cyl)

parameters to be used for BIOS calculations are:
cylinders=487 heads=255 sectors/track=63 (16065 blks/cyl)

Media sector size is 512
Warning: BIOS sector numbering starts with sector 1
Information from DOS bootblock is:
The data for partition 1 is:
sysid 0 (0000),(unused)
    start 0, size 454656 (222 Meg), flag 80 (active)
        beg: cyl 0/ head 0/ sector 1;
        end: cyl 221/ head 63/ sector 32
The data for partition 2 is:
sysid 239 (0xef),(EFI System Partition)
    start 3440, size 896 (0 Meg), flag 0
        beg: cyl 1023/ head 254/ sector 63;
        end: cyl 1023/ head 254/ sector 63
The data for partition 3 is:
<UNUSED>
The data for partition 4 is:
<UNUSED>
```
and 
```
% gpart show /dev/da4
=>     63  7831489  da4  MBR  (3.7G)
       63     3377       - free -  (1.6M)
     3440      896    2  !239  (448K)
     4336  7827216       - free -  (3.7G)
```
Only the second partition on the disk appears mountable, it is formatted with FAT and contains only these files
```
find ./
./
./efi
./efi/boot
./efi/boot/bootx64.efi
```

I will reboot and look at it from Linux, also try to rewrite the stick or mount the img locally...

**Comment by r0m30** [comment]
That's not the PBA image.  The PBA image is a single partition with a vfat filesystem that contains a /boot/syslinux directory with msedpba.c32, syslinux.cfg, a few lib*.c32 and the syslinux loader.

I downloaded the PBA from r0m30.com and it hasn't been changed.

What are the commands you are using to create this USB stick and to load the PBA to the shadow MBR?

**Comment by h-2** [comment]
Wow, I was just redownloading the stuff comparing checksums and I realised, I did one of the most stupid mistakes you can make: I forgot to gunzip the files :poop:

Lol. I cant believe it, sorry for the noise regarding that. Now I can boot the rescue from usb and after reflashing the (right) PBA, I also get the prompt upon booting! Hurray. 

However, it won't accept my password unfortunately. It says booting from (hd0,0), but then it asks me for the password again. I set both the admin1 password and the SID-password to the same 5-letter combination (no special keys, no region specific ones) and it still doesn't work. Any ideas?

Thanks for your help!

**Comment by r0m30** [comment]
What does it say about the drive?  
Did you enable locking range 0?  If the Locking range isn't enabled but the MBREnable flag is set you will get that behavior.

**Comment by r0m30** [comment]
Any progress?

**Comment by h-2** [comment]
I have just --setMBRenable again, than also set locking range 0, but the behaviour is the same. It won't accept the password...
Is there a way I can dump info from the device and you can check whether it is set up correctly?

Thanks!

**Comment by r0m30** [comment]
Are you using a non-US keyboard layout?

If that's the case then let's try somthing simpler before we start tracing.

Turn off OPAL mode.  http://www.r0m30.com/msed/documentation/managing/removeopal
Setup the rescue image: http://www.r0m30.com/msed/documentation/managing/testrescue
Put the PBA somewhere where you can access it from the rescue image. 
Then setup the drive while running the rescue image.

That should insure that the pass phrase is entered using the US keyboard layout.

If that doesn't work we can run some traces.

**Comment by h-2** [comment]
> Are you using a non-US keyboard layout?

I am, so I intentionally picked only lower case letters and only those that are in the same place as on US (German keyboard only differs in 'y' and 'z' for the regular letters). My previous behaviour was kind of noobish, but I am very certain these letters are the same, I use US layout quite often. But I can change the password to just the letter 'a' later just to make sure :)

**Comment by r0m30** [comment]
I believe the issue should be in one of these areas.
1. The keyboard scan code reading in the PBA.
2 The password hashing in the PBA, possibly related to the way the drive serial number is handled.
3. FreeBSD is doing something "helpful" to the identify information or possibly not doing the word swap like Linux (Ubuntu is my test platform)

What does msed show when you do a query on the drive?  I'm interested in how it shows the drive serial number as compared to a program like hdparm.

If your "a" password experiment fails then we would need traces.
First from msed (first step makes it so you don't expose any real password info so if you don;t use password make sure you use something equally useless)
msed --setAdmin1Pwd <currrentpassword> password /dev/???
msed -vvvvv --setAdmin1Pwd password test /dev/??? >msed_trace.txt 2>&1

To trace the PBA, transfer it to a usb stick and then change the line in /boot/syslinux/syslinux.cfg that says append NOTRACE  to append TRACE. When you boot the usb stick the PBA will hex dump information and then wait for the enter key before proceeding so you can either write it down or snap a pic with your cell phone.

**Comment by h-2** [comment]
I have the log file and snapshots of the trace, do you have an e-email-address that I can send them to?

And what do you mean by:

> 3. FreeBSD is doing something "helpful" to the identify information or possibly not doing the word swap like Linux (Ubuntu is my test platform)

Is there any way I can check? Does the syslinux expect any certain disk layout or partition table? 

Thanks for your help!

**Comment by r0m30** [comment]
Use the email in the copyright statement r0m30@r0m30.com

The identify information is defined as 256 16bit words in big endian
format.  That means the model,firmware and serial number are mangled in a
little endian system.  The Linux identify fixes this automatically, windows
doesn't.  You should be able to tell by executing a msed query and seeing
how the model, firmware and serial number are displayed.

On Mar 7, 2015 1:41 PM, "Hannes Hauswedell" <notifications@github.com>
wrote:
>
> I have the log file and snapshots of the trace, do you have an
e-email-address that I can send them to?
>
> And what do you mean by:
>>
>> FreeBSD is doing something "helpful" to the identify information or
possibly not doing the word swap like Linux (Ubuntu is my test platform)
>
> Is there any way I can check? Does the syslinux expect any certain disk
layout or partition table?

**Comment by h-2** [comment]
> Use the email in the copyright statement r0m30@r0m30.com

I have sent you the files.

> The identify information is defined as 256 16bit words in big endian
format.  That means the model,firmware and serial number are mangled in a
little endian system.  The Linux identify fixes this automatically, windows
doesn't.  You should be able to tell by executing a msed query and seeing
how the model, firmware and serial number are displayed.

But I can't run msed on FreeBSD anyway, only from Linux (they are not compatible and the msed code uses Linux specifics). Is there any documentation on the specific linux behaviour so I might find out how this is done on FreeBSD?

Thanks!

**Comment by h-2** [comment]
How does the chainloading work in particular, I believe more and more that we might have a problem there..
Does it chainload a disk or a partition on the disk? (hd0,0) suggests a partition, but how does it chose which one? And are there limitation to the supported partition schemes or even the partition types?

The reason I also asked this earlier was that I am using a GPT partitioning scheme. This has been default on FreeBSD since quite some time, also on BIOS-pcs. The reason why I think that something might not be working, is that I have tried changing the bootme attribute and the legacy_bios_boot attribute to other partitions than the default(first) but the BIOSPBA still wants to boot (hd0,0).

Thanks for your help!

**Comment by r0m30** [comment]
The functionality is from the syslinux chain.32 module,  hd0,0 means to chain load the boot drive using the MBR.

Looking at the PBA trace, there is only one screenshot and it's not of the full screen.  If that's all you got then the issue is that the PBA isn't recognizing your stat/ahci chip.  I still need to sit down and walk through what you did capture but a lspci from your machine would help.

**Comment by r0m30** [comment]
The only storage controller listed in the trace you sent me is an IDE controller.  The PBA is looking for a SATA/AHCI controller.  I thought I asked earlier what mode you had your bios in but I don't see it now.  Is there an option to set you're disk controller to AHCI mode in your bios?

**Comment by h-2** [comment]
Ah, unbelievable. I was 100% sure it was set to ahci, because I always set my bioses to ahci to avoid weird issues with compatibility problems in freebsd. BUT IT WASNT :imp: 
Now it is, and it is actually working, awesome! 

Sorry, for this super complicated thread. If I can send you 10$ via something to say thanks, let me know!

**Comment by r0m30** [comment]
Excellent!
No need for any payment.
