### ISSUE TITLE
Identify failed Invalid argument

### ISSUE THREAD

**Issue by pathfinderfs** [r0m30/msed#12]
When performing msed --scan I am getting the following on my Samsung 850 EVO  (currently hooked up via USB).

- 19:25:34.556 ERR : Identify failed Invalid argument
/dev/sdc No 

And if I do msed --query /dev/sdc I get 

- 19:27:08.024 ERR : Identify failed Invalid argument
- 19:27:08.024 ERR : Invalid or unsupported disk /dev/sdc

Any ideas on what I'm doing wrong?

Thanks!
David

**Comment by r0m30** [comment]
Msed only supports sata attachments.

________
Mike

**Comment by pathfinderfs** [comment]
That explains it -- Thanks!
