### ISSUE TITLE
Stuck on "About to chainload hd0,0 Booting..."

### ISSUE THREAD

**Issue by sebouh00** [r0m30/msed#13]
Hi. I followed the steps written in the [documentation](http://www.r0m30.com/msed/documentation/managing), but I ended up stuck on "about to chainload hd0,0 booting..." for 10 mins after I powered on the laptop and entered the passphrase. I disabled LockingRange and set MBREnabled to off via the rescue disk to be able to start windows again.

Can someone please advise what went wrong? Or was I too impatient? Let me know what information you need and I'll supply it here.

Notebook: Lenovo T440s
OS: Windows 8.1
HDD: SAMSUNG MZ7TE256HMHP-000L7 (OPAL 2)

Thanks.

**Comment by r0m30** [comment]
No, you weren't to impatient, the OS should start immediately.  Does it say
it unlocked the drive?  What happens if you reboot (ctl+alt+del)  don't
power off after you enter the passphrase and it hangs ?

Do you have any other OS's installed on the disk?

________
Mike

**Comment by sebouh00** [comment]
I don't have another OS installed.

After I enter the pass phrase, it shows:
Found device SAMSUNG MZ7TE256HMHP-000L7            is OPAL unlocked
About to Chainload hd0,0 Booting...

Pressing ctl+alt+del after this does nothing.

**Comment by r0m30** [comment]
Wow, it's so hung that it won't do a soft reboot, that's unfriendly.
It unlocked the drive and called the chain loader, so it's failing in that code.

Can you build a test pba (see http://www.r0m30.com/msed/documentation/managing/testpba-1) and test it as described

then edit the syslinux.cfg changing the line
append NOTRACE
to 
append NOTRACE hd1,0
then test boot again

We need to find an option that allows the syslinux chainloader to work with your bios.  Unfortunately there are lots of options and hd0,0 is the one that SHOULD work universally on a correctly implemented bios.

other options to try are
append NOTRACE boot
append NOTRACE hd1,1
append NOTRACE hd1,2

**Comment by sebouh00** [comment]
Okay. I tried to test boot with the different configs.

NOTRACE: Doesn't hang. Shows hd0,0 booting then goes back to enter pass phrase.
NOTRACE hd1,0: hangs on booting.
NOTRACE boot: Doesn't hang. Shows "about to chainload boot Booting..." and goes back to enter pass phrase.
NOTRACE hd1,1: Can't find an OS.
NOTRACE hd1,2: Can't find an OS.

The pba I originally flashed with --loadPBAimag was the default one on the website (append NOTRACE), so how come it doesn't hang here but it does when in actual boot phase?

**Comment by r0m30** [comment]
OK, check what mode windows is running in.
http://www.eightforums.com/tutorials/29504-bios-mode-see-if-windows-boot-uefi-legacy-mode.html

It's looking like your computer is checking what type of drive is being
booted and setting up legacy/UEFI mode based on whether the disk is GPT or
MBR.  The PBA is legacy/MBR and Windows is UEFI/GPT.

________
Mike

**Comment by sebouh00** [comment]
It's running in UEFI mode. It won't boot in legacy mode.

**Comment by r0m30** [comment]
The current PBA is for biios machines only.  You have two choices for running msed, 
1 reinstall windows in legacy mode.
2 Wait for the UEFI PBA.  (I'm working on multiple ranges right now and plan on taking a break before I start on the UEFI PBA so it could be a while.)

You could also try setting up eDrive which is supposed to be included in Windows 8.1

**Comment by sebouh00** [comment]
I understand. Thanks for your help though.

**Comment by r0m30** [comment]
Support for 64 bit UEFI  machines is available in the Drive-Trust-Alliance/sedutil repo.  See the wiki for downloads and instructions.

All further development will be in the DTA repo.
