### ISSUE TITLE
Invalid PCI header type 10

### ISSUE THREAD

**Issue by mutex9** [r0m30/msed#14]
Hello, testing PBA (on a pendrive) failed. 
Motherboard: Gigabyte GA-970A-D3
SSD: Samsung 850 Pro
Msed version: 0.21beta

I added TRACE argument to get more info.  
"Found SATA controller in AHCI mode on the PCI buss @ 80008800
vendor/product 43911002, class 01060140, misc@+0c 00002010
Invalid PCI header type 10
<several of DID .. SDID .. CLASS - can list them if relevant>"

msed on a rescue disk seems to work - output of query on /dev/sda

"/dev/sda ATA Samsung SSD 850 PRO 1TB                  EXM01B6Q S1SRNWAF808246F     
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = N, Alignment Granularity = 1 (512), Logical Block size = 512, Lowest Aligned LBA = 0
Opal V1.0 function (0x0200)
Base comID = 0x1004, comIDs = 1
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0"  

--
Anyway, it's great that this project exists.

**Comment by r0m30** [comment]
What do you have the OnChip SATA type (integrated peripherals screen) set to in your bios? 
The PBA is written specifically to support AHCI mode.

**Comment by mutex9** [comment]
AHCI.

**Comment by r0m30** [comment]
The doc on PCI that I could find doesn't mention anything about a 0x10 header type.  Obviously that's incomplete.  

There is a test PBA in the specialtesting folder on www,r0m30.com/msed/files
Can you give that a try?

**Comment by mutex9** [comment]
Now it works, as in, it finds my ssd and correctly tells it's OPAL and not locked.  
Is that test PBA good for a real install on a ssd?

**Comment by r0m30** [comment]
It's on my primary machine.

**Comment by mutex9** [comment]
Everything works now! I have TCG OPAL encryption enabled. You can add me as a success report.  
Thanks!

**Comment by r0m30** [comment]
I keep forgetting to delete that page, I haven't updated it since the early alpha releases.
