### ISSUE TITLE
PBA not working for me (but msed is)

### ISSUE THREAD

**Issue by mamandell** [r0m30/msed#15]
I'm using a Lenovo Thinkpad X61 Tablet with a Seagate ST500LT025 as the sole drive.  I have msed working fine:  Using it on the rescue disk, I can successfully lock and unlock the SED, set it to do PBA, etc.  Drive shows up on --scan as OPAL 2 and --query correctly shows the state.

However, when I use the PBATest or PBA directly from the SED,  it does not show the drive information or unlock the drive.  Output looks like this:

    Msed PBA for BIOS machines

    Enter Pass Phrase to unlock OPAL SSC drives>****
    About to Chainload hd0,0 Booting...

    SYSLINUX 6.03 etc etc

It does not appear to unlock the disk or turn off the shadow MBR -- I cannot get the PBA to actually boot the drive. 

Thanks in advance if you can help.

**Comment by r0m30** [comment]
Does that device have bios settings?  If it does check to see if the disk
controller is configured in ahci mode.

On the pbatest edit the syslinux.cfg, change the line that says append
NOTRACE to append TRACE so we can see what the PCI bus devices are.

________
Mike

**Comment by mamandell** [comment]
Yes, definitely in ahci mode.  Results of trace attached.
![image](https://cloud.githubusercontent.com/assets/6607900/6645118/273ad718-c990-11e4-92af-cfedceaf0690.png)

**Comment by r0m30** [comment]
The trace isn't complete. In trace mode the program pauses and waits for an enter key so you can see and record the traces.  What does the trace say for the next screen(s)?

**Comment by mamandell** [comment]
Sorry. Here's the rest.
![image](https://cloud.githubusercontent.com/assets/6607900/6645742/6fea1e9c-c995-11e4-9b1a-de14f40f4be9.png)

**Comment by r0m30** [comment]
The device is in "Slumber" state, I'm looking for the device to be active.  I'll need to do some research to find out what I need to do to transition it to "active" state.

**Comment by r0m30** [comment]
As a quick test can you disabled Aggressive Link Power Management in your bios and see if the PBA works?

**Comment by mamandell** [comment]
I turned off power management to PCI; no change.

Also, I tried doing PBA from the SED with TRACE, and got exactly the same output.  It's hard to understand how the device can be in "slumber" when it is used as the boot device.

**Comment by r0m30** [comment]
AHCI has a feature called Device initiated power management that allows the device to enter slumber state as soon as there are no I/O's pending.  When you are entering the passphrase that takes an eternity in computer time so the device will enter slumber mode.  This is supposed to lower the battery drain.

I need to do some more reading to see how to handle this.  When I think I have it figured out I'll post a new PBA to the specialtesting folder and let you know.

**Comment by r0m30** [comment]
There is a test PBA in the specialtesting section of the files section. 
biospba-issue15.img

**Comment by mamandell** [comment]
Thanks.  After entering pass phrase, it says "Found device " and hangs.

**Comment by r0m30** [comment]
Naturally, it's never that easy.
Try this one.
biospba-issue15a.img

**Comment by mamandell** [comment]
Same result

**Comment by r0m30** [comment]
Grrrrr

According to the doc you should be able to turn it off without stopping the port.  Let me see if I can work it into the initialization code.

**Comment by r0m30** [comment]
It printed the "Found device" ?

**Comment by mamandell** [comment]
Absolutely.
![image](https://cloud.githubusercontent.com/assets/6607900/6653322/8f059ed6-ca63-11e4-8b92-b5224513bcab.png)

**Comment by r0m30** [comment]
That means either we have a new problem or I uploaded the wrong PBA image.  Can you run it with trace?

**Comment by mamandell** [comment]
Pretty much the same. 
![image](https://cloud.githubusercontent.com/assets/6607900/6653371/f5b69372-ca65-11e4-92f0-ec2dfa04d21c.png)
![image](https://cloud.githubusercontent.com/assets/6607900/6653372/fd3a23fc-ca65-11e4-9481-bb3489b6f1a9.png)

**Comment by r0m30** [comment]
That's really strange........

Yet another test  - biospba-issue15c.img

Trace is already turned on, I really only need any screen where it shows the SSTS and the last screen of the trace.

**Comment by mamandell** [comment]
![image](https://cloud.githubusercontent.com/assets/6607900/6653679/b732c272-ca71-11e4-85c2-9567c4ed5402.png)

**Comment by r0m30** [comment]
Well at least it's a new problem.  I'll have to take a closer look at the code.  It looks like the IO isn't completing or returning an error. Certainly the flags I'm checking aren't being set.

**Comment by r0m30** [comment]
After looking at the code vs the ahci and sata specs I can't find any issues..... I'm not saying there isn't one but I can't find it. 

I'm guessing that it's something to do with the aggressive power management in your laptop.  

At this point I believe the only way I would be able to create a working PBA for your machine is to build one based on a linux micro distribution.  This is certainly doable, there are however two issues.  The PBA would be substantially larger (over 10x larger) so it would take over half an hour to load it to the drive.  The PBA would not be able to chain load the OS so you would have to go through an additional boot whenever you unlocked the drive making startup time much longer as well.

**Comment by mamandell** [comment]
I do have all power management turned off in the bios so that is a very irritating problem.  Anyway, thanks for all the extra work.
