### ISSUE TITLE
drive not found (PBA not working)

### ISSUE THREAD

**Issue by kforner** [r0m30/msed#17]
Hello,

I just tried the PBA with biospba-0.22beta.img on a HP Z800 that has a LSI SAS 1068E HBA (in IT mode), and a SAMSUNG 850 EVO 500Gb, and it does not find any drive.

Thanks,
Karl

**Comment by r0m30** [comment]
The PBA is looking for a AHCI controller in SATA mode, if it doesn't find one then it doesn't probe for disk devices.  That HBA looks like a hybrid SAS/SATA controller but I couldn't find any info on IT mode with a quick search so I'm not sure what that is or how it would present itself to when I scan the PCI bus.  Do you know of any programming doc for that controller?  Does it accept the same FIS structure as an AHCI/SATA HBA?

**Comment by kforner** [comment]
On Fri, Mar 27, 2015 at 7:27 PM, r0m30 <notifications@github.com> wrote:

> The PBA is looking for a AHCI controller in SATA mode,
>

In the BIOS I selected the AHCI(+RAID) mode (instead of IDE).

if it doesn't find one then it doesn't probe for disk devices.
>


> That HBA looks like a hybrid SAS/SATA controller
>
Yes it is, and also a RAID controller


> but I couldn't find any info on IT mode with a quick search so I'm not
> sure what that is or how it would present itself to when I scan the PCI
> bus.
>


> Do you know of any programming doc for that controller?
>
No.


> Does it accept the same FIS structure as an AHCI/SATA HBA?
>
No idea what a FIS structure is.

What can I do to help you solve this ?

Thanks,

Karl

**Comment by r0m30** [comment]
Are you using raid? If not can you disable it?

To trace the PBA you will need to build a test PBA on a USB stick, see here http://www.r0m30.com/msed/documentation/managing/testpba-1
Then edit the syslinux.cfg and change the line that says append NOTRACE to append TRACE save it and boot the USB stick.  The PBA will dump out critical values and structures as it proceeds then stop so you can take a picture of it, after you take the picture press enter to continue.  Post/send the pictures and I'll see what I can figure out.

**Comment by kforner** [comment]
> Are you using raid? If not can you disable it?
>
No I'm not, the HBA has been flashed in IT (non-RAID) mode


> To trace the PBA you will need to build a test PBA on a USB stick, see
> here http://www.r0m30.com/msed/documentation/managing/testpba-1
> Then edit the syslinux.cfg and change the line that says append NOTRACE to
> append TRACE save it and boot the USB stick. The PBA will dump out critical
> values and structures as it proceeds then stop so you can take a picture of
> it, after you take the picture press enter to continue. Post/send the
> pictures and I'll see what I can figure out.
>

**Comment by kforner** [comment]
Here are the test PBA pictures:

![mse_boot1](https://cloud.githubusercontent.com/assets/122744/6893014/9896432a-d6c9-11e4-8e9a-7abf373ff014.jpg)
![mse_boot2](https://cloud.githubusercontent.com/assets/122744/6893013/98956ee6-d6c9-11e4-81c7-45a72f9ca5ff.jpg)

**Comment by r0m30** [comment]
It looks like your devices are behind a PCI bridge.  There is not currently any code in the PBA to support PCI bridges.  

It's looking like I may need to develop a second PBA the uses a full linux distro to support this type of system, unfortunately a PBA like that would also reboot instead of chain load.

**Comment by kforner** [comment]
On Tue, Mar 31, 2015 at 3:24 AM, r0m30 <notifications@github.com> wrote:

> It looks like your devices are behind a PCI bridge. There is not currently
> any code in the PBA to support PCI bridges.
>
I don't know, but it's not an external card plugged in a PCI port.
But I plan to purchase a PCI HBA (a Highpoint Rocker 640L), so I guess
there will be a problem too.



> It's looking like I may need to develop a second PBA the uses a full linux
> distro to support this type of system, unfortunately a PBA like that would
> also reboot instead of chain load.
>
What is the problem with the reboot ? increased boot time ?

Thanks

**Comment by r0m30** [comment]
It depends on if your motherboard routes the PCI slots through the bridge or not.  I have no way of knowing.

Yes, the reboot extends the (re)start time.

**Comment by kforner** [comment]
update: the Samsung ssd is recognized using the Highpoint Rocket 640L card !!!

**Comment by r0m30** [comment]
Great.  That's good to hear.
