### ISSUE TITLE
Feedback using msed with a samsung EVO ssd on a highpoint 640L with a HP Z800

### ISSUE THREAD

**Issue by kforner** [r0m30/msed#18]
Hello,

Just to share my experience:
Everything is working great and I am extremely grateful for msed, without which the SED on my Samsung would have been wasted !!

Using the Highpoint Rocket 640L for the Samsung EVO 850 500 GB had two benefits: first to be able to use drive at full speed, and second, to have it recognized my msed.

The rescue disk does not work though: my disk is not recognized. I used a ubuntu 14.04 usb boot disk, on which I copied the msed executable and pba image. 

Thanks

**Comment by r0m30** [comment]
I would guess that the module necessary to run the card is missing from the TinyCore kernel.  Do you kinw which module is required to run the card?

**Comment by kforner** [comment]
No. How can I tell ?

**Comment by r0m30** [comment]
sudo lspci -k 

the output will list the Kernel driver in use for each device on the PCI bus.

**Comment by kforner** [comment]
This seems to correspond to the SATA card. But I guess this is a standard module.

```
42:00.0 SATA controller: Marvell Technology Group Ltd. Device 9230 (rev 10)
        Subsystem: Marvell Technology Group Ltd. Device 9230
        Kernel driver in use: ahci
        Kernel modules: ahci
```

**Comment by r0m30** [comment]
Yes, that is a standard module,  I honestly don't know what to do next to get the card working on the rescue system.  It almost has to be a kernel configuration issue but I have no way of testing.

**Comment by kforner** [comment]
Maybe just add in the doc the use of the ubuntu live-cd as a work-around

**Comment by r0m30** [comment]
I've updated the rescue system to Tiny Core 6.2, can you see if that fixes your issue?

**Comment by kforner** [comment]
Sorry for the delay. I confirm that the new version of the testPBA works for me.
Thank you !
