### ISSUE TITLE
Windows 8.1 is unresponsive after waking up

### ISSUE THREAD

**Issue by sebouh00** [r0m30/msed#20]
Hi. I finally got msed working with BIOS configuration. The only problem I have now is when I wake the device from sleep. I get the login screen, but I can't login. Windows doesn't register when I type the password and on-screen buttons (like power, accessibility, etc.) don't respond either. The mouse works fine.

I've disabled msed and the problems are gone. I realize there's something going on here, maybe the storage device is being powered off when asleep and waking it up requires unlocking again? Just wondering if this is a known problem or it's to be expected.

Details:
Notebook: Lenovo T440s
OS: Windows 8.1 x64
HDD: SAMSUNG MZ7TE256HMHP-000L7 (OPAL 2)

**Comment by r0m30** [comment]
Yes, there is currently no support for sleep only hibernation.

________
Mike

**Comment by sebouh00** [comment]
Okay, thanks.
