### ISSUE TITLE
PBA test on USB stick failed

### ISSUE THREAD

**Issue by n1c0las** [r0m30/msed#21]
Hi, I tested PBA image (0.22beta) on USB stick as it is advised here : http://www.r0m30.com/msed/documentation/managing/testpba-1
But my SSD (Crucial_CT256MX100SSD1 ) is not identified.
I have a laptop Lenovo Thinkpad X200 (legacy BIOS mode, AHCI is on). Single OS is on SSD (Windows 7 professional N).
TestRescue image was working fine:
![2015-04-21_13-55-47](https://cloud.githubusercontent.com/assets/12063605/7269641/005a6ffe-e8d6-11e4-848c-3085a546f9fc.JPG)
![2015-04-21_13-56-07](https://cloud.githubusercontent.com/assets/12063605/7269645/04b22b28-e8d6-11e4-823e-a8557dca91b4.JPG)
![2015-04-21_13-56-39](https://cloud.githubusercontent.com/assets/12063605/7269618/d3b229ec-e8d5-11e4-877d-c96539ab5da2.JPG)

And output of hdparm :
![2015-04-21_13-57-40](https://cloud.githubusercontent.com/assets/12063605/7269678/48dad6c4-e8d6-11e4-9b89-426b1e1bebc0.JPG)
![2015-04-21_13-58-00](https://cloud.githubusercontent.com/assets/12063605/7269691/592c4c38-e8d6-11e4-9ce4-eb38b5ba3cf9.JPG)
![2015-04-21_13-59-45](https://cloud.githubusercontent.com/assets/12063605/7269693/5bcf9044-e8d6-11e4-83d1-edf5ab73c2d8.JPG)
![2015-04-21_14-00-17](https://cloud.githubusercontent.com/assets/12063605/7269696/60c66348-e8d6-11e4-88be-574f1844be2c.JPG)
![2015-04-21_14-00-48](https://cloud.githubusercontent.com/assets/12063605/7269699/633de966-e8d6-11e4-94b0-e2c431be2748.JPG)
![2015-04-21_14-01-06](https://cloud.githubusercontent.com/assets/12063605/7269706/65c9880c-e8d6-11e4-9ed6-f22f568aa43f.JPG)

After I unplug SSD and plug it again, I type password again at the prompt and I can get "Found device " without reference of SSD.
![2015-04-21_21-36-36](https://cloud.githubusercontent.com/assets/12063605/7269560/371623ae-e8d5-11e4-8c3e-84851cdaa701.JPG)

Here are pictures of output with "TRACE" enable :
![2015-04-22_09-04-09](https://cloud.githubusercontent.com/assets/12063605/7269429/3fdbb9f0-e8d4-11e4-9e4a-1242d9c2dc5d.JPG)
![2015-04-22_09-04-44](https://cloud.githubusercontent.com/assets/12063605/7269433/45350780-e8d4-11e4-91ad-4bab94000616.JPG)
![2015-04-22_09-05-09](https://cloud.githubusercontent.com/assets/12063605/7269437/4779c008-e8d4-11e4-9937-140d50314f1e.JPG)

I tried also other options such as 
append NOTRACE hd1,1
append NOTRACE hd1,2 to syslinux.cfg

Well, I don't know if I made a mistake somewhere.
Thank in advance for the help !

**Comment by r0m30** [comment]
It seems that the Lenovo Laptops are using aggressive power management and I haven't figured out how to successfully wake the drive.  I'm working on an alternative PBA that is based on a the rescue system, it is a lot larger and will require a reboot instead of being able to chainload.  I need to block out several hours to test and debug it before I unleash it on an unsuspecting world.

**Comment by n1c0las** [comment]
Thanks! I will check if I can change some settings about power management in BIOS.
Anyway, it's a great job you did there!

**Comment by r0m30** [comment]
There is a Linux based PBA in the special testing section of the files on r0m30.com if you'd like to give that a try.

**Comment by n1c0las** [comment]
Thanks a lot, I will try this image this evening.

**Comment by n1c0las** [comment]
Well, I tried this image and here is what is happening : kernel is loading, then pass phrase is asked to me. I type it, then PC boots and asks for pass phrase again.
I don't see SSD identified.

**Comment by r0m30** [comment]
I totally missed that the output wasn't flushed in the release code.  I'm not that familiar with ncurses.  I uploaded the Debug version of the Linux PBA to the special testing section.  It will stop and show you the results before exiting to the command prompt.  

Meanwhile I'll have to look into the fflush() equivalent for ncurses.

**Comment by n1c0las** [comment]
Thanks. Results of the command are : 
"Scanning..."
"Unlocking /dev/sda Failed"
Then I type enter and there is a prompt root@box#

**Comment by r0m30** [comment]
OK it recognized the drive.  If you haven't set up the drive it with will
fail to unlock because the password hasn't been set.  You should be good to
set up the encryption.

________
Mike

**Comment by n1c0las** [comment]
Yes, password was not set yet. I set up the password and locked the drive with Rescue usb drive, it seems to work!
After I did it I had to power off the PC, then I boot on linux PBA and I could unlock the drive by typing password.
![img_2685](https://cloud.githubusercontent.com/assets/12063605/7442517/21ac0d60-f115-11e4-88e7-44b571789fdf.JPG)
