### ISSUE TITLE
msed build error: 'aligned_alloc' was not declared in this scope

### ISSUE THREAD

**Issue by alec-stuart** [r0m30/msed#22]
Hi r0m30,
Awesome work on the project.
I'm trying to build  msed on a Kali linux (Debian based) livecd, and I'm getting a build error as below:

root@kali:~/msed# make CONF=Release_x86_64
./GitVersion.sh > msed/Version.h
"make" -f nbproject/Makefile-Release_x86_64.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory `/root/msed'
"make"  -f nbproject/Makefile-Release_x86_64.mk dist/Release_x86_64/msed
make[2]: Entering directory `/root/msed'
mkdir -p build/Release_x86_64/GNU-Linux-x86/msed
rm -f "build/Release_x86_64/GNU-Linux-x86/msed/MsedOptions.o.d"
g++ -m64   -c -O2 -Werror -s -Imsed/linux -Imsed -std=c++11 -MMD -MP -MF "build/Release_x86_64/GNU-Linux-x86/msed/MsedOptions.o.d" -o build/Release_x86_64/GNU-Linux-x86/msed/MsedOptions.o msed/MsedOptions.cpp
mkdir -p build/Release_x86_64/GNU-Linux-x86/msed/linux
rm -f "build/Release_x86_64/GNU-Linux-x86/msed/linux/MsedDevOS.o.d"
g++ -m64   -c -O2 -Werror -s -Imsed/linux -Imsed -std=c++11 -MMD -MP -MF "build/Release_x86_64/GNU-Linux-x86/msed/linux/MsedDevOS.o.d" -o build/Release_x86_64/GNU-Linux-x86/msed/linux/MsedDevOS.o msed/linux/MsedDevOS.cpp
msed/linux/MsedDevOS.cpp: In member function 'virtual void MsedDevOS::identify()':
msed/linux/MsedDevOS.cpp:180:87: error: 'aligned_alloc' was not declared in this scope
make[2]: *** [build/Release_x86_64/GNU-Linux-x86/msed/linux/MsedDevOS.o] Error 1
make[2]: Leaving directory `/root/msed'
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory `/root/msed'
make: *** [.build-impl] Error 2
root@kali:~/msed# 

Looks like this C vs C++ issue: http://stackoverflow.com/questions/29247065/compiler-cant-find-aligned-alloc-function

root@kali:~/msed# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5) 

Any ideas on this?

**Comment by r0m30** [comment]
alligned_alloc was added in C11.  I have gotten one other report of this
issue and they fixed it by using a more current library.  I use Xubuntu so
I can't help with how to use upstream libraries in Debian.

----------
Mike

**Comment by r0m30** [comment]
Any progress?

**Comment by alec-stuart** [comment]
Hi,
I updated all my packages and still got the error.
I was running low on time and ended up using your binaries which worked
great on my Samsung 850 PRO.

Prior to msed I had tried using hdparm to set the ATA password, it seems my
BIOS wouldn't allow hdparam to lock/unlock from userland .


Thanks so much for all your efforts!

**Comment by zhouska** [comment]
I have created a pull request to address this problem. I'm running most recent Kali Linux x86_64.

**Comment by r0m30** [comment]
Hey!

 

New message, please read <http://funezy.com/head.php?jnf16>

 

Sergio Martins

**Comment by brendanhoar** [comment]
WARNING:

I think that last link may be malware.

**Comment by brendanhoar** [comment]
Yup, the funezy.com link is spam and/or malware.

http://support.clean-mx.com/clean-mx/portals.php?domain=funezy.com&sort=id%20DESC

**Comment by r0m30** [comment]
Sorry,
Some spammer has started using the r0m30 email to send out his garbage.  I deleted the post.

**Comment by r0m30** [comment]
Hey!

 

New message, please read <http://ilmar.info/hat.php?0>

 

r0m30@r0m30.com

**Comment by brendanhoar** [comment]
Is this another spam msg, Mike?

**Comment by r0m30** [comment]
Yep, yet another one.....  grrrrrr

**Comment by r0m30** [comment]
Hey!

 

Open message <http://colunna.com.br/lose.php?j>

 

r0m30@r0m30.com

**Comment by brendanhoar** [comment]
More spam.

**Comment by r0m30** [comment]
Hey!

 

Open message <http://genovayacht.com/legs.php?ftce7>

 

r0m30@r0m30.com

**Comment by brendanhoar** [comment]
More spam...
