### ISSUE TITLE
when writing LINUXPBADebug: One or more header fields have 0 length

### ISSUE THREAD

**Issue by cranderson** [r0m30/msed#23]
I have a Crucial M550 SSD, testing on a Optiplex GX620.  Apparently there is no AHCI BIOS support on this system, so I couldn't get biospba working.   Now I'm trying the Linux PBA and I get this error when trying to load it:

`# ./msed --loadPBAimage pw LINUXPBADebug-0.23beta.img /dev/sda
- 01:17:02.056 INFO: Writing PBA to /dev/sda
 \ [********             ]- 01:21:00.848 ERR : One or more header fields have 0 length
- 01:21:00.878 ERR : One or more header fields have 0 length
- 01:21:00.878 ERR : EndSession Failed`

**Comment by r0m30** [comment]
I tested on the EVO 850, my m500 fails too.  This is a strange one. I can write the regular PBA to it, but the LinuxPBAs fail.  Is yours failing at different numbers of asterisks too?  I've got a trace just need to figure out what is going on.

**Comment by cranderson** [comment]
Yes, the last time was 5 asterisks.  It almost sounds like a timeout or size issue.  Maybe the drive needs to do garbage collection or something and the command times out during that?  Can you have it do retries instead of just punting when this happens?

**Comment by r0m30** [comment]
Retry fails :(
Need to figure out if a restart will work.

Looks like a firmware bug at this point.

The spec calls for 128MB of storage for the PBA shadow table and the
LINUXPBA* loads and boots on both Samsung EVO & Seagate.

I'm going to be traveling next week so it may be a while before I get a
workaround coded.

________
Mike

**Comment by cranderson** [comment]
I updated my firmware to MU02, as well as tried limiting SATA link speed to 1.5G and using a different SATA controller (SiI 3132 PCIe card), but these didn't help.  Finally, I made the LINUXPBA image much smaller by building my own linux 4.0.4 kernel with the bare minimum config, no modules, and paring down core.gz.  The LINUXPBA, now only 7MiB uncompressed, was able to install fine to the M550 SSD.  Basically,Tiny Core Linux is overkill for a PBA, so I ended up ripping out most of the fancy stuff and just hardcoding linuxpba into the init script after some basic initialization including udevd.

**Comment by r0m30** [comment]
I tried building my own micro distro but it ended up just as big as tiny
core.  Do you have some pointers?

And there is still a bug in the Crucial firmware this just avoids it.

----------
Mike

**Comment by n1c0las** [comment]
Same problem here when I try to load LinuxPBA on MX100 - Windows 7 x64 (I tried firmware MU1 and MU2), if it can help.

**Comment by cranderson** [comment]
See here for my workaround for this issue:  https://github.com/cranderson/buildroot-linuxpba
I used "buidroot" to build a 4MB LinuxPBA image (it could actually be smaller, less than 3MB if desired).
The nice thing about this method is it is entirely self-hosted and built from source.

**Comment by r0m30** [comment]
Thanks,  this should be really helpful to people with Crucial Drives.  I'm goint to look into using this instead of tiny core.

**Comment by Cysioland** [comment]
I also have this issue. Crucial MX100.

* BIOSPBA — doesn't unlock my device, had to resort to unlocking it via rescue
* LinuxPBA — One or more header fields have 0 length

**Comment by brianjmurrell** [comment]
I have this problem on an INTEL SSDSC2BF240A5 also.

@cranderson: Do you have a binary LinuxPBA built using "buildroot" that can be downloaded from somewhere?

**Comment by brianjmurrell** [comment]
@cranderson: NM.  I built one.  Still need to actually try rebooting this machine to see if it works, but it did build.

**Comment by r0m30** [comment]
@brianjmurrell 

I've uploaded a BIOS64_PBA.img to the SpecialTesing folder of the files section.  It is still a little rough but it loads and works on a MX200.  It's 64bit only.

**Comment by cranderson** [comment]
FYI, I fixed some issues with the buildroot-linuxpba build and I also provided a pre-built image.  If you were having trouble building it, or if you were having trouble with some USB keyboards, try the new version:

https://github.com/cranderson/buildroot-linuxpba

**Comment by r0m30** [comment]
This is a bug in msed.  Crucial is the only vendor that I have run into that uses a non-zero session timeout.  I hope to have this fixed soon.

**Comment by r0m30** [comment]
I've posted a testfix file for this issue on r0m30.com.   It's issue23.zip in the special testing section on the files page.  This should allow loading the LinuxPBA on Crucial drives.

**Comment by Cysioland** [comment]
Doesn't work

```
- 11:55:57.459 ERR : One or more header fields have 0 length
- 11:55:57.459 ERR : Properties exchange failed
```

When I --loadPBAImage and --query

**Comment by r0m30** [comment]
@Cysioland   What HBA is on your motherboard?  Is there a special driver required?

**Comment by Cysioland** [comment]
@r0m30 If you're talking about my SATA controller, then
`00:1f.2 SATA controller: Intel Corporation 82801IBM/IEM (ICH9M/ICH9M-E) 4 port SATA Controller [AHCI mode] (rev 03)
`

**Comment by r0m30** [comment]
@Cysioland  Yep, that's what I'm asking about.  I haven't had any reports on problems with Intel controllers.  There is another report of an MX200 working on the #16 issue and it works on my system so I'm thinking it's something unique to your system.  Do you have Intel RST installed?

**Comment by Cysioland** [comment]
I installed nothing in this matter except a standard Ubuntu 15.04.

**Comment by r0m30** [comment]
OK, my testing is on Xubuntu 14.x  Let me see about setting up a test system on 15.04.

**Comment by r0m30** [comment]
This issue should be fixed in the Drive-Trust-Alliance/sedutil repo, see the wiki for download links.

The Crucial Drives are the only ones I've run into that limit the session time.

@Cysioland  We'll continue to work on your issue(s) on #31
