### ISSUE TITLE
Question about Erace

### ISSUE THREAD

**Issue by rennyo** [r0m30/msed#24]
Hi r0m30!
Thank you for your work! It saved me a lot of time.. Just tested your last version 0.23b on UEFI bios with CSM enabled with Samsung 850 Pro. Everything works. Have a question, may be you know...
The disk has a key which is encrypting with user SID. If I change SID, "disk key" will be re-encrypted. If I want to delete ALL the data from disk(secure erase I mean) and regenerate "disk key" should i use --reverttper with locking enabled or I should use --PSIDrevert?

**Comment by r0m30** [comment]
Locking needs to be enabled for either to work but after that both generate
a new encryption key, "crypto erasing" the drive.  The only difference is
the user who performs the task.  If you look at the code you will see that
reverttper and PSIDRevert both use the same call, they just pass a
different user and password when they authenticate to the drive.

This is NOT the same as a "secure erase", the ATA spec says that the drive
is to be overwritten with data that should make the data irretrievable.
The "crypto erase" just destroys the current encryption key and generates a
new one, the data is left in place but encrypted (AES-256 on the EVOs) with
an unknown key.

Last I checked it would take more time than the universe is believed to
have existed so far to brute force the encryption.  That doesn't take into
account the weakness of the password which could be attacked much easier.

<RANT>
All bets are off if the encryption is improperly implemented or (insert
your favorite three letter agency here) has coerced the vendor into
weakening the encryption.  Isn't it wonderful that our government is so
protective of us that they a willing to violate the constitution that they
swore to obey with impunity to keep us safe from whatever bogy man they can
conjure up to scare us
</RANT>.

----------
Mike
