### ISSUE TITLE
TestPBA not working on laptop

### ISSUE THREAD

**Issue by doveman** [r0m30/msed#26]
I've installed a Samsung 850 Evo 120GB SSD in my Acer Travelmate 5720. After writing the biospba-0.23beta.img to a USB stick, I can boot from it but after it prompts for the password and I enter something, it just says "Found device", nothing more and gets stuck there and the laptop's fan spins up, so it's presumably pegging the CPU at 100%.

I queried the drive with msed from Windows 8.1 x64 and that looks OK, so I guess it's something in the Linux boot image that's incompatible with the laptop hardware:

\\.\PhysicalDrive0 ATA Samsung SSD 850 EVO 120GB                EMT01B6Q S21UNSBG128294K     
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = N, Alignment Granularity = 1 (512), Logical Block size = 512, Lowest Aligned LBA = 0
Opal V1.0 function (0x0200)
Base comID = 0x1004, comIDs = 1
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 9
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0 , Reverted PIN = 0x0 , comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1

**Comment by doveman** [comment]
Oops, just noticed the LinuxPBA image on the downloads page, I'll try that.

**Comment by doveman** [comment]
With LINUXPBARelease-0.23beta.img, it just reboots after I enter a password.

With LINUXPBADebug-0.23beta, it shows "Failed to unlock /dev/sda1, Device not compatible /dev/sdb1"

**Comment by r0m30** [comment]
The debug one says it recognized and tried to unlock the drive.  If you
haven't enabled locking yet then that is the expected response.  I can't
figure out how to flush the screen using curses so the output isn't showing
up on the release PBA.
________
Mike

**Comment by doveman** [comment]
Ah, OK. I was expecting it to show the output shown here http://www.r0m30.com/msed/documentation/managing/testpba-1

I've tested with the Rescue img and that works fine. I'm not sure which img I should be writing to the SSD now though, as per these instructions http://www.r0m30.com/msed/documentation/managing as the biosPBA isn't compatible with my laptop and the LINUXPBARelease just reboots after entering a password . Would the LINUXPBADebug be OK to write to the SSD, or will that just drop to a commandline as it did when I tested booting it from USB?

**Comment by r0m30** [comment]
Yep, I suck at documentation. The Linux PBA doesn't have the same output,
it was added to support mobile computers with aggressive power management.
The Linux PBAs will reboot after unlocking to allow the bios to reset the
hardware..  The release version is the one for daily use.

________
Mike

**Comment by doveman** [comment]
OK, cool. I'm loading the LINUXPBARelease img with --loadPBAimage at the moment and it's taken about 15mins so far to get half-way, so I presume it must be doing more than just loading the image to the shadow MBR table, maybe it's doing the encryption of my (120GB) SSD at this point as well?

**Comment by r0m30** [comment]
No all it's doing is loading the PBA. See the FAQ for an explanation.
Something I did document  :-)

________
Mike

**Comment by doveman** [comment]
Ah yes I see that now, sorry I overlooked that.

Well I'm happy to report it's all working well now. Thanks for your help and indeed for creating this tool :)

**Comment by r0m30** [comment]
Not a problem.
