### ISSUE TITLE
msed working well but wave doesn't. 

### ISSUE THREAD

**Issue by novachoi** [r0m30/msed#27]
it's on testing WAVE and msed at the same time, but only have trouble on WAVE  tool not msed. 

Reproduce way (WAVE)
1. initialize with password '1111'
2. change password from '1111' to '2222' (working well)
3. trying sign in with '2222' after reset device (not in users or wrong password)

i've tried it on msed
1. initialsetup 
2. setAdmin1Pwd '1111' to '2222'
3. enableLockingRange 0 
4. it's working well with '2222' after reset. 

do you have any idea or experience as like above? (and i also have crucial m500 device)

**Comment by r0m30** [comment]
Hi,
I think what you are asking is can you use WAVE and msed together, if not then reply back and I'll try and answer your real question.

Short answer: NO.

Long answer:
Msed uses the ADMIN1 user and a PBKDF2<SHA1> hash (salt=drive serial no, iterations =75000) to randomize your password before passing it the OPAL subsystem.  See https://en.wikipedia.org/wiki/PBKDF2
I have no knowledge of what, if any, password hashing WAVE uses.  Unless a product uses the same user and hashing described above it will not inter-operate with msed.

**Comment by novachoi** [comment]
Hi, r0m30

Thanks to your comment. and short answer is No

I've tested these after re-install firmware every testing, so it's not sharing the password msed & WAVE.
And, i already tested password changing after initialize process on Wave,  before  reset(reboot) device, so i think it's not a problem of PBKDF2 hash thing. 

Very first, i think it's the problem of my opal engine in firmware, but it's works well on msed even though reset device.

**Comment by r0m30** [comment]
I don't have any experience with WAVE so I'm not sure what the issue is.  It could be a problem with the PBA not properly supporting your computer.  I know msed has issues with some power management states in the lightweight PBA but when the management program is run under the OS it works fine.
