### ISSUE TITLE
Support the Samsung external SSD T1 (USB3 with UAS)

### ISSUE THREAD

**Issue by er-nun-vogelfrei-ist** [r0m30/msed#33]
These are fairly new in the market:

http://www.samsung.com/global/business/semiconductor/minisite/SSD/global/html/portablessdt1/overview.html

They use a proprietary application for both OS X and Windows to initialize the disk. It does not respond to standard utilities like Samsung Magician for querying the OPAL status. However I believe these are indeed OPAL based, or at least could be supported in Linux if we reverse engineer the OS X kernel extension and Windows applications used to manage it.

When running msed it fails since it is not a SATA attachment:

```
- 14:06:40.024 ERR : Identify failed Invalid argument
```

This would be a nice feature enhancement, since it will most likely open support for external SSDs in generic USB3 enclosures with UAS support :)

**Comment by r0m30** [comment]
Supporting generic USB drives via UAS is being discussed.  I don't see us spending the time necessary to reverse engineer proprietary formats.  It just isn't an efficient use of the resources we have available.  If you follow the Drive-Trust-Alliance/sedutil repo that is where this functionality would be added.

**Comment by brendanhoar** [comment]
Re: considering UAS support - that would be great. That would open up being
able to administer secondary drives (or drives that will be primary drives
in other machines) from a drive admin workstation would be very beneficial
to uptake of sedutil, I believe. UAS would make that more possible, esp.
under Windows (which normally does some sneaky things to SATA-attached OPAL
drives).
