### ISSUE TITLE
PBA interoperable?

### ISSUE THREAD

**Issue by brianjmurrell** [r0m30/msed#34]
Hi,

I wonder if msed is interoperable with other OPAL PBA implementations such as, oh, say, McAfee.

IOW, if I have a disk that was OPAL encrypted with McAfee, can I put msed on it and unlock in Linux what was locked in McAfee?

Do I need to put the PBA on the disk to do it or can I unlock it using a bootable USB disk somehow?

**Comment by r0m30** [comment]
To my knowledge msed is not interoperable with any other sed software,  If they were to publish what userids they use and if/how they hash the password then it could be made to work.

**Comment by brianjmurrell** [comment]
Hrm.  It seems that OPAL is a bit more complicated than I thought.  I didn't imagine the concept of (multiple?) usernames and alternatives to password hashing, etc.  I thought it was simply "what is the password" and that password was used to unlock the encryption key for the disk (ranges).  :-(

It seems a poor standard that is not interoperable between implementations.  :-(
