### ISSUE TITLE
sedutil?

### ISSUE THREAD

**Issue by wp9015362** [r0m30/msed#35]
@r0m30 :

First of all: Thanks for having created an open source tool to manage TCG OPAL.

I haven't tried it yet, but it's nice that something like that is available.

I've got a few questions:

First of all, [you announced that you joined forces with the DTA and that new SED software should be arriving soon from the DTA](https://github.com/r0m30/msed/blob/DTAannounce/README.md).

So, I had a look at the [DTA GitHub account](https://github.com/Drive-Trust-Alliance) and they have two repositories.

One of them is sedutil:

https://github.com/Drive-Trust-Alliance/sedutil

where most of the commits seem to come from you.

I am wondering:

Will sedutil be the successor of msed? Or what exactly is it?

And when will it be released? I saw [the DTA website says something about a new website coming on 2015-10-15](https://www.drivetrust.com/). Will that be the release date of sedutil?

And how exactly is sedutil different from msed?

Regards

**Comment by r0m30** [comment]
Yes, sedutil is the successor to msed.  We expect to release the first version of sedutil when the web site launches.  Today sedutil is msed with a few bug fixes, we are using it a the base for the DTA Open Source effort.  We are working on plans to enhance sedutil in the future.
