### ISSUE TITLE
Is it possible to have "suspend to RAM" working on linux?

### ISSUE THREAD

**Issue by tarruda** [r0m30/msed#38]
I was playing with msed and a newly acquired Samsung 850 EVO SSD and noticed that after enabling the drive lock feature suspend no longer works correctly: When the laptop resumes, all kinds of bug start happening because the OS fails to read from the disk.

At first I thought it was a bug, but then I saw your comment in a [blog post](http://vxlabs.com/2015/02/11/use-the-hardware-based-full-disk-encryption-your-tcg-opal-ssd-with-msed/) explaining that suspend to ram is not supported because the PBA is not called during resume.

At least to me, having the ability to suspend the laptop is essential, especially because hibernate is pretty much broken on linux. Ideally we should not need to re-enter the passphrase on wake up(Is it possible for msed to send a "sleep command" to the drive so it won't be locked on wake up?)

I have two questions:

- Is it possible to have suspend to RAM working on linux running on a OPAL-compliant SED?
- If so, what needs to be done?

**Comment by r0m30** [comment]
@tarruda 

I believe it is possible to get S3 working on Linux.  From my limited research I believe that a kernel module would need to be developed that would run during the resume processing and unlock the drive(s).  It would need to execute some time after the disk drivers reinitialize but before the system resumes disk activity.

You said that you would not want to re-enter the drive passphrase.  That would require storing it somewhere, probably the TPM on newer devices.  I currently do not store the passphrase anywhere, so a secure method of storing the passphrase for retrieval would also need to be added to the PBA.
