### ISSUE TITLE
can't hibernate 

### ISSUE THREAD

**Issue by fab128** [r0m30/msed#39]
Hello
First Thanks for this great software.
I'm using a Samsung SSD 850 evo on a Samsung N140 netbook and Fedora 22.
The syslinux PBA was not working (keep asking the password and do nothing else). I installed the linuxPBA which seems to work well.
However, when I do an hibernate and power up again, Fedora just starts up as if I did a normal power off.
Here is what happens in details:
- The first boot after hibernate, the BIOS says "system resuming...", but boots the PBA since the drive is locked
- after I entered the passphrase, the PBA does a soft reboot
- The BIOS now do not says anymore "system resuming", and in fact the system is not resuming, but starts up normally.

Thanks in advance for your help

**Comment by r0m30** [comment]
I'm not sure I tested hibernation with the LINUXPBA to be honest.  I'll try it here in the next few days and let you know what I come up with

**Comment by r0m30** [comment]
I can't reproduce this on my machine,  I'm going to have to install linux on one of my seds to test further.

**Comment by fab128** [comment]
I found that there was actually an issue with Fedora 22 not configured properly for hibernation (see http://blog.ordinatechnic.com/blog/2015/06/08/enabling-hibernation-suspend-to-disk-in-fedora-22/) !

Following the steps described, I managed to get hibernate working with linuxPBA.

Sorry for that that wasn't a bug with msed.
