### ISSUE TITLE
method status code NOT_AUTHORIZED when doing initial setup

### ISSUE THREAD

**Issue by iamsergio** [r0m30/msed#40]
$ sudo ./msed --initialsetup password /dev/sdb
- 01:41:46.037 ERR : method status code NOT_AUTHORIZED
- 01:41:46.038 ERR : Session start failed
- 01:41:46.063 ERR : One or more header fields have 0 length
- 01:41:46.063 ERR : EndSession Failed
- 01:41:46.063 ERR : takeownership failed
- 01:41:46.063 ERR : Initial setup failed - unable to take ownership

$ ./msed --query /dev/sdb

/dev/sdb ATA Samsung SSD 850 EVO 500GB                EMT01B6Q S21JNXAG518687L     
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = N, Alignment Granularity = 1 (512), Logical Block size = 512, Lowest Aligned LBA = 0
Opal V1.0 function (0x0200)
Base comID = 0x1004, comIDs = 1
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 9
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1

**Comment by r0m30** [comment]
Do you by chance has another drive with Windows and BitLocker/eDrive active?

**Comment by iamsergio** [comment]
I have two other drives, used by Windows, but BitLocker is disabled.
And they don't support Opal

**Comment by lellis1936** [comment]
Works fine on my SSD, same model.   If you have already done 'initialsetup' once before you will get this.  That's a one-time function.

**Comment by r0m30** [comment]
@lellis1936 do you have Windows installed?  If so, what version and tier (home, pro etc).

**Comment by lellis1936** [comment]
Yes, Windows 7 Ultimate.  I had same error as poster when I inadvertently tried running initialsetup more than once.  Aside from that, MSED works fine for me after following the setup guide (EVO Pro 850 SSD).  That's to say, running initialsetup the first time resulted in no error message and everything else worked as expected.

**Comment by r0m30** [comment]
@lellis1936 Running initialsetup twice will certainly cause the NOT_AUTHORIZED error.  This is the second report of this behavior where the person reporting says that they did not previously run intialsetup.  In both cases they have Windows on another drive,  I'm wondering if Windows (at 8.1+ possibly) sees an OPAL drive that has not had the default password changed and so they take ownership of the drive.  This is not necessarily a bad thing, a drive that still is in the factory default state could be easily loaded with a ransomware PBA and locked.  This would happen so fast that you wouldn't even be see it until it was too late.  At least with the SW encryption ransomware you have the possibility of noticing that the attack is going on and shutting down before all your files are encrypted.

But this is all speculation as Microsoft isn't going to tell us if this is happening or not.

**Comment by brendanhoar** [comment]
Mike,

Could it be eDrive being provisioned by Windows 8.x/10? This cuts off
access to both OPAL and ATA password functionality.

http://answers.microsoft.com/en-us/windows/forum/windows8_1-hardware/sed-edrive-unprovisioning/87148920-e749-4e8a-b674-d8d8d551981d

**Comment by r0m30** [comment]
@brendanhoar That's my guess, but like I said before MS isn't going to tell us for sure when and how Windows "provisions" OPAL drives.  I've gotten to the point where I disconnect every other drive in my system when I install/repair Windows because it assumes that it owns the entire machine.  After all you have windows, why would you want any other OS ..... right.

**Comment by r0m30** [comment]
Well I can now confirm that an OPAL drive that has not had it's password changed will be "provisioned" by Windows 10 Pro, as far as I can tell there is no way to recover the password used by windows.

And now I'm off to reinstall Windows 10 :-(

**Comment by brendanhoar** [comment]
Yeah. :(

That's why I manually set the ATA Password on OPAL / eDrive supporting boot
drives before letting Windows 8/10 see them. That blocks the eDrive
provisioning.
