### ISSUE TITLE
S3 Sleep Question

### ISSUE THREAD

**Issue by lellis1936** [r0m30/msed#45]
S3 sleep is handy and I have resorted to using a program which allows execution of scripts on sleep and resume.  The scripts I use unlock the drive just before entering sleep and lock it on resume.  This works consistently but it is not ideal.

Would you mind commenting on whether it is technically possible to support S3 with Opal and whether you plan to support it in future?   If so, would it work as I've described or would it prompt for an unlock password on resume? 

Hibernate is much slower and is a nuisance due to the large HIBERFIL.SYS file required.  I know about the inherent security risks of sleep (especially while drive is unlocked), and wonder if it is possible to do better with some kind of integrated S3 support.

**Comment by r0m30** [comment]
My cursory research indicates that it is possible.  I think that it would require a kernel module/windows driver.  I would like to support it in the future but do not have a plan or timeline at this point.
