### ISSUE TITLE
msed (Windows 7) - not working, i need help

### ISSUE THREAD

**Issue by HDW1** [r0m30/msed#46]
Hi, i need help.

My hardware: Samsung Evo 850 - 250 GB
OS: Windows 7 - 64 bit

Problem:

When i start msed.exe and scan (msed --scan), msed saying me this:

![msed-error1](https://cloud.githubusercontent.com/assets/15739456/11043348/887946d2-871c-11e5-8043-2d1e4368b243.jpg)

I have burned the PBA image and tested it.
It say´s : Found Device Samsung SSD 850 EVO 250GB             is OPAL Not Locked

I have also burned the rescue image, when this image is loaded i can use the msed --scan command, but there is no biosPBA image on rescue image to load the biosPBA image on my Evo 850. 

How can i use msed with Windows 7 for initialsetup (bootdrive)?

I tested linux Kubuntu 14 and downloaded the linux msed, but kubuntu can not start the msed file and in the terminal i become only errors. It says: cant run msed.

Can you help me please to setup msed for my bootdrive?

**Comment by r0m30** [comment]
Hi,
I'm not sure what's wrong, I develop on a Win7 64bit system and test using a Samsung EVO 850.  Do you know what HBA (disk controller chip) your system is using?  
A trace might help as well, try issuing msed -vvvvv --query \\.\PhysicalDrive0 > debug.txt to get one.

Msed has been superseded by Drive-Trust-Alliance/sedutil  there are more recent versions available from that repo.

**Comment by HDW1** [comment]
Thanks for the help :-)

My mainboard:
GA-970A-DS3P (rev. 1.0) - http://www.gigabyte.us/products/product-page.aspx?pid=4591#ov

HBA: (i hope you mean this)
AMD SATA
Driverdate: 23.09.2014
Driver version: 1.2.1.376

msed -vvvvv --query \.\PhysicalDrive0 > debug.txt < this file is empty but i have a screenshot:

![msed-trace](https://cloud.githubusercontent.com/assets/15739456/11068773/3daa8d98-87d3-11e5-8980-be8dbbd9b1dd.jpg)


It´s weird - if i boot from rescue image - msed will recognizes the 850 Evo (msed --scan command). There is no biospba image on rescue disc so i can´t upload it to mbr.

**Comment by r0m30** [comment]
It looks like the markdown ate one of the backslashes on the device name, there are 2 backslashes, a period, one backslash then PhysicalDrive followed by a number starting at 0.  Look at the output from the scan above.

I'm wondering if the AMD SATA driver is blocking the trusted send/receive commands?

**Comment by r0m30** [comment]
I didn't ut the PBAs on the rescue disk to keep the download size reasonable.

**Comment by HDW1** [comment]
Hmm... what can i do to find out if the AMD SATA driver blocks the commands? Should I use a different driver?

or:

The rescue image works for me. Can you put the PBA image on the rescue disk and i will do the initialsetup and upload  the PBA with the rescue disk? Or is this wrong an Windows 7 will not boot because the AMD SATA driver blocks the commands?

**Comment by r0m30** [comment]
You can try contacting AMD, but that is usually not very productive as a consumer.

You could put the PBA on another stick and mount it while you are in the rescue image.  I don't really want to make the rescue image bigger.  

PS - newer versions of the software are available at Drive-Trust-Alliance/sedutil

**Comment by r0m30** [comment]
I didn't address your question about the AMD driver, sorry.
The AMD driver won't be an issue because the PBA runs under Linux so you shouldn't have any problems with it unlocking the drive if the rescue image works.

**Comment by HDW1** [comment]
"You could put the PBA on another stick and mount it while you are in the rescue image."

What is the command for this?

**Comment by r0m30** [comment]
If you only have one hard drive in your system this should get you there, if you have nore HD in you system then you'll have to adjust the /dev/sdb to be whatever is the last drive in your system.
After you boot the rescue system Linux is running from RAM so you can remove that USB, insert the USB with the PBA and then it should look something like this:

mkdir /PBA
mount -t vfat /dev/sdb /PBA
msed --loadPBAimage password /PBA/pbafilename.img /dev/sda

**Comment by HDW1** [comment]
mkdir /PBA    <--- works
mount -t vfat /dev/sdb /PBA <--- errormessage: mounting /dev/sdb on /PBA failed: Invalid argument

I have only the SSD connected with the mainboard and the stick on the usb port. The SSD is /dev/sda (msed --scan) and the stick is sdb.

I´m confused^^

**Comment by r0m30** [comment]
Try the mount without the -t vfat
mount /dev/sdb /PBA

**Comment by HDW1** [comment]
mkdir /PBA <--- works
"mount /dev/sdb /PBA" <--- errormessage: mounting /dev/sdb on /PBA failed: Invalid argument

**Comment by HDW1** [comment]
"PS - newer versions of the software are available at Drive-Trust-Alliance/sedutil"

I have downloaded sedutil (sedutil-cli.exe) but i have exact the same problem.

**Comment by HDW1** [comment]
Please, i need really help. Can you please make an exception an put the biospba image on the rescue disk?

I did everything what you said but i can´t upload the biospba from the stick on the ssd-drive because i can´t mount the usbstick from OS on the rescuedisk.

I can´t use msed / sedutil on windows because msed will not work. I tried Kubunt and Fedora Linux. On this OS is the problem that i can´t edit the "allow_tpm" file and set it from 0 to 1. When i trying to save this file i become a errormessage - and yes, i´m logged in as root.

**Comment by r0m30** [comment]
I want to get the mount correct so that someone installing can can pick the PBA they want.
Looking back at this I made a mistake....
try mount -t vfat /dev/sdb1 /PBA or mount  /dev/sdb1 /PBA 
notice the 1 following the sdb.

**Comment by HDW1** [comment]
mkdir /PBA <--- ok
mount -t vfat /dev/sdb1 /PBA <--- ok

msed --loadPBAimage password /PBA/pbafilename.img /dev/sda <--- error:

- 19:52:15.916 ERR : method status code INVALID_Parameter
- 19:52:15.916 ERR : Session start failed
- 19:52:15.941 ERR : One or more header fields have 0 length
- 19:52:15.942 ERR : End Session Failed

I'm not sure where the error is...

**Comment by r0m30** [comment]
Have you done the initialsetup?
