### ISSUE TITLE
QUESTION: How do I get the drive to generate a new media encryption key?

### ISSUE THREAD

**Issue by ole-de** [r0m30/msed#7]
Hi,

does the right procedure go like this? Assuming a factory new drive:

msed --initialsetup passwd /dev/sdx
msed --reverttper passwd /dev/sdx

Thanks, Ole

**Comment by r0m30** [comment]
Yes, that will generate a new key, and crypto erase ALL the data on the
drive.

 I haven't coded the on the fly rekey functions at this point.  I still
need to investigate if both OPAL 1.0 and 2.0 have rekey as a mandatory
function and implement it the same way.

----------
Mike
